### ISSUE TITLE
 fetchd query wasm list-code --log_format json prints output in plain text instead of json

### ISSUE THREAD

**Issue by MissingNO57** [fetchai/fetchd#108]
I am running local-net using fetchd in feature/stargate branch

```
fetchd query wasm list-code --log_format json
code_infos:
- builder: ""
  code_id: "1"
  creator: fetch1a3n8ndap8xd37vwljthv8sdsk6d7xx9mwfhq7n
  data_hash: 4D3A9F90A8E46925DE05A5B03533DD0A89AF49232E8071C6BF3BC0B0BC833F72
  source: ""
pagination:
  next_key: null
  total: "0"
```
